curl -X POST http://localhost:4000/sse/push -H 'Content-Type: application/json' -d '{"sessionId":"1","threadId":"thread-2","data":{"type":"textNode","text":"Your 3 most recent roles:<ul><li><strong>Senior Backend Engineer</strong> — Gurugram · ₹28–40 LPA · 18 applicants · Live</li><li><strong>Product Designer</strong> — Remote (India) · ₹18–26 LPA · 42 applicants · Live</li><li><strong>QA Automation Lead</strong> — Bengaluru · ₹22–30 LPA · 7 applicants · Closing</li></ul>","actions":["Post a job","Review applicants"],"data":{}}}'

curl -X POST http://localhost:4000/sse/message -H 'Content-Type: application/json' -d '{"sessionId":"1","threadId":null}'

curl -X POST https://actor-acts-fantastic-capture.trycloudflare.com/sse/push -H 'Content-Type: application/json' -d '{"sessionId":"1","threadId":"thread-1","data":{"type":"welcomeScreen","text":"You have <strong>12 live roles</strong> at Astranova Mobility and 34 new applicants since Friday. What should we do first?","actions":["Post a job","View my jobs","Review applicants","Draft an outreach note"],"data":{"greeting":"Good morning, Meera.","company":"Astranova Mobility","options":[{"id":"post-job","label":"Post a job","description":"Draft, screen and publish in a minute","icon":"plus","variant":"primary"},{"id":"view-jobs","label":"View my jobs","description":"12 live · 3 closing this week","icon":"briefcase","variant":"secondary"},{"id":"review-applicants","label":"Review applicants","description":"34 new, 9 shortlist-ready","icon":"user","variant":"secondary"}]}}}'

curl -X POST http://localhost:4000/sse/push -H 'Content-Type: application/json' -d '{"sessionId":"1","threadId":"thread-3","data":{"type":"jobPostingForm","text":"Let'\''s build it. I pre-filled what I know from your last SDE hire — edit anything.","actions":[],"data":{"title":"New job posting","step":"Step 1 of 2","submitLabel":"Continue","fields":{"title":"SDE-1","description":"Build and ship customer-facing features across our rider and driver apps. You will own services end to end with a small, senior team and pair closely with design.","location":"Hybrid — Gurugram","experience":"1-3 Yrs","salary":"₹12–18 LPA"},"skills":["React","TypeScript","Node.js","REST APIs"]}}}'

curl -X POST https://actor-acts-fantastic-capture.trycloudflare.com/sse/push -H 'Content-Type: application/json' -d '{"sessionId":"1","threadId":"thread-4","data":{"type":"questionsBuilder","text":"Want to add a screening questionnaire? Roles with 3 questions get <strong>2.4× better shortlists</strong>.","actions":[],"data":{"title":"Screening questionnaire","step":"Step 2 of 2","questions":[{"id":"question-1","type":"radio","label":"How many years of production React have you shipped?","options":["0–1 years","1–3 years","3+ years"]}]}}}'

curl -X POST http://localhost:4000/sse/push -H 'Content-Type: application/json' -d '{"sessionId":"1","threadId":"thread-5","data":{"type":"jobCard","text":"Published. <strong>SDE-1</strong> is live on 4 boards — I'\''ll surface matches here as they land.","actions":["Post another job","View my jobs","Invite candidates","Boost this post"],"data":{"title":"SDE-1","company":"Astranova Mobility","status":"Live","location":"Hybrid — Gurugram","experience":"1-3 Yrs","salary":"₹12–18 LPA","description":"Build and ship customer-facing features across our rider and driver apps. You will own services end to end with a small, senior team and pair closely with design.","skills":["React","TypeScript","Node.js","REST APIs"],"questionsNote":"1 screening question attached","shareLabel":"Share link"}}}'
