curl -X POST http://localhost:4000/sse/push -H 'Content-Type: application/json' -d '{"sessionId":"1","threadId":"thread-2","data":{"type":"textNode","text":"Your 3 most recent roles:<ul><li><strong>Senior Backend Engineer</strong> — Gurugram · ₹28–40 LPA · 18 applicants · Live</li><li><strong>Product Designer</strong> — Remote (India) · ₹18–26 LPA · 42 applicants · Live</li><li><strong>QA Automation Lead</strong> — Bengaluru · ₹22–30 LPA · 7 applicants · Closing</li></ul>","actions":["Post a job","Review applicants"],"data":{}}}'

curl -X POST http://localhost:4000/sse/message -H 'Content-Type: application/json' -d '{"sessionId":"1","threadId":null}'

curl -X POST https://sao-jazz-model-wages.trycloudflare.com/sse/push -H 'Content-Type: application/json' -d '{"sessionId":"1","threadId":"thread-1","data":{"type":"welcomeScreen","text":"You have <strong>12 live roles</strong> at Astranova Mobility and 34 new applicants since Friday. What should we do first?","actions":["Post a job","View my jobs","Review applicants","Draft an outreach note"],"data":{"greeting":"Good morning, Meera.","company":"Astranova Mobility","options":[{"id":"post-job","label":"Post a job","description":"Draft, screen and publish in a minute","icon":"plus","variant":"primary"},{"id":"view-jobs","label":"View my jobs","description":"12 live · 3 closing this week","icon":"briefcase","variant":"secondary"},{"id":"review-applicants","label":"Review applicants","description":"34 new, 9 shortlist-ready","icon":"user","variant":"secondary"}]}}}'

curl -X POST http://localhost:4000/sse/push -H 'Content-Type: application/json' -d '{"sessionId":"1","threadId":"thread-3","data":{"type":"jobPostingForm","text":"Let'\''s build it. I pre-filled what I know from your last SDE hire — edit anything.","actions":[],"data":{"title":"New job posting","step":"Step 1 of 2","submitLabel":"Continue","fields":{"title":"SDE-1","description":"Build and ship customer-facing features across our rider and driver apps. You will own services end to end with a small, senior team and pair closely with design.","location":"Hybrid — Gurugram","experience":"1-3 Yrs","salary":"₹12–18 LPA"},"skills":["React","TypeScript","Node.js","REST APIs"]}}}'

curl -X POST https://sao-jazz-model-wages.trycloudflare.com/sse/push -H 'Content-Type: application/json' -d '{"sessionId":"1","threadId":"thread-4","data":{"type":"questionsBuilder","text":"Want to add a screening questionnaire? Roles with 3 questions get <strong>2.4× better shortlists</strong>.","actions":[],"data":{"title":"Screening questionnaire","step":"Step 2 of 2","questions":[{"id":"question-1","type":"radio","label":"How many years of production React have you shipped?","options":["0–1 years","1–3 years","3+ years"]}]}}}'

curl -X POST http://localhost:4000/sse/push -H 'Content-Type: application/json' -d '{"sessionId":"1","threadId":"thread-5","data":{"type":"jobCard","text":"Published. <strong>SDE-1</strong> is live on 4 boards — I'\''ll surface matches here as they land.","actions":["Post another job","View my jobs","Invite candidates","Boost this post"],"data":{"title":"SDE-1","company":"Astranova Mobility","status":"Live","location":"Hybrid — Gurugram","experience":"1-3 Yrs","salary":"₹12–18 LPA","description":"Build and ship customer-facing features across our rider and driver apps. You will own services end to end with a small, senior team and pair closely with design.","skills":["React","TypeScript","Node.js","REST APIs"],"questionsNote":"1 screening question attached","shareLabel":"Share link"}}}'

curl -X POST https://sao-jazz-model-wages.trycloudflare.com/sse/push -H 'Content-Type: application/json' -d '{"sessionId":"2","threadId":"thread-6","data":{"type":"welcomeScreen","text":"<strong>4 recruiters</strong> viewed your profile this week and 12 new job openings match your skills. What should we do first?","actions":["Update your profile","View openings","Application status"],"data":{"greeting":"Welcome back, Rhea.","options":[{"id":"update-profile","label":"Update your profile","description":"Keep your skills and resume current","icon":"edit","variant":"primary"},{"id":"view-openings","label":"View openings","description":"12 new roles match your profile","icon":"briefcase","variant":"secondary"},{"id":"application-status","label":"Application status","description":"2 in review · 1 interview scheduled","icon":"clipboard","variant":"secondary"}]}}}'

curl -X POST https://sao-jazz-model-wages.trycloudflare.com/sse/push -H 'Content-Type: application/json' -d '{"sessionId":"2","threadId":"thread-7","data":{"type":"profileUpdateForm","text":"Let'\''s keep things current. Update anything that'\''s changed and I'\''ll refresh your matches.","actions":[],"data":{"title":"Update your profile","submitLabel":"Save profile","fields":{"name":"Rhea","preferredRole":"Frontend Engineer","preferredLocation":"Remote (India)","experience":"2-4 Yrs","expectedCtc":"₹18–24 LPA"},"keySkills":["React","TypeScript","Node.js"]}}}'

curl -X POST https://sao-jazz-model-wages.trycloudflare.com/sse/push -H 'Content-Type: application/json' -d '{"sessionId":"2","threadId":"thread-8","data":{"type":"applicationStatusList","text":"Here'\''s where things stand across your <strong>4 active applications</strong>.","actions":["View openings","Update your profile"],"data":{"title":"Application status","applications":[{"id":"application-1","jobTitle":"SDE-2","location":"Gurugram","ctc":"₹18–24 LPA","status":"Shortlisted"},{"id":"application-2","jobTitle":"Frontend Engineer","location":"Remote (India)","ctc":"₹16–20 LPA","status":"Interview scheduled"},{"id":"application-3","jobTitle":"Backend Engineer","location":"Bengaluru","ctc":"₹20–28 LPA","status":"Under review"},{"id":"application-4","jobTitle":"Full-stack Developer","location":"Hybrid — Pune","ctc":"₹15–19 LPA","status":"Not selected"}]}}}'

curl -X POST https://sao-jazz-model-wages.trycloudflare.com/sse/push -H 'Content-Type: application/json' -d '{"sessionId":"2","threadId":"thread-9","data":{"type":"jobOpeningCard","text":"Found a fresh match. <strong>Frontend Engineer</strong> at Bright Path Technologies lines up well with your profile.","actions":["View openings","Application status"],"data":{"title":"Frontend Engineer","company":"Bright Path Technologies","status":"New","location":"Remote (India)","experience":"2-4 Yrs","salary":"₹16–20 LPA","description":"Own our design system and ship customer-facing UI across web and mobile, pairing closely with product and design.","skills":["React","TypeScript","Next.js","Design systems"],"applyLabel":"Apply now","referralLabel":"Ask for referral"}}}'

curl -X POST http://localhost:4000/sse/push -H 'Content-Type: application/json' -d '{"sessionId":"3","threadId":"thread-10","data":{"type":"referralApprovalCard","text":"<strong>Rhea Kapoor</strong> is asking for a referral to <strong>Frontend Engineer</strong> — here'\''s how they match up.","actions":[],"data":{"title":"Referral request","candidate":{"name":"Rhea Kapoor","experience":"4 Yrs","location":"Remote (India)"},"job":{"title":"Frontend Engineer","location":"Remote (India)","ctc":"₹16–20 LPA"},"matchScore":92,"approveLabel":"Approve","rejectLabel":"Reject"}}}'

curl -X POST https://sao-jazz-model-wages.trycloudflare.com/sse/push -H 'Content-Type: application/json' -d '{"sessionId":"2","threadId":"thread-10","data":{"type":"textNode","text":"You'\''re all set. I'\''ve submitted your application for <strong>Frontend Engineer</strong> — I'\''ll let you know as soon as the recruiter responds.","actions":["View openings","Application status"],"data":{}}}'

curl -X POST https://sao-jazz-model-wages.trycloudflare.com/sse/push -H 'Content-Type: application/json' -d '{"sessionId":"2","threadId":"thread-11","data":{"type":"textNode","text":"Done. I'\''ve asked your connections about a referral for <strong>Frontend Engineer</strong> — I'\''ll update you here.","actions":["View openings","Application status"],"data":{}}}'
